### ISSUE TITLE
make_cffi.py incorrectly finds compiler

### ISSUE THREAD

**Issue by Arfrever** [indygreg/python-zstandard#103]
`make_cffi.py` incorrectly finds compiler:
- It does not call [customize_compiler()](https://github.com/python/cpython/blob/e488e300f5c01289c10906c2e53a8e43d6de32d8/Lib/distutils/sysconfig.py#L173-L243) function, which would make code respect user-set `CC` environmental variable.
- It uses `compiler.executables["compiler"]`, which is only a class-default non-customized value. `compiler.compiler` should be called instead.

Compare:
```
$ CC="x86_64-pc-linux-gnu-gcc" python -c 'import distutils.ccompiler; compiler = distutils.ccompiler.new_compiler(); print(compiler.executables["compiler"])'
['cc']
$ CC="x86_64-pc-linux-gnu-gcc" python -c 'import distutils.ccompiler; compiler = distutils.ccompiler.new_compiler(); distutils.sysconfig.customize_compiler(compiler); print(compiler.compiler)'
['x86_64-pc-linux-gnu-gcc']
```

Patch: [make_cffi.patch.txt](https://github.com/indygreg/python-zstandard/files/4602124/make_cffi.patch.txt)

**Comment by indygreg** [comment]
Good find! I'll commit this patch shortly. Thank you!

**Comment by Arfrever** [comment]
You have not applied the last part of patch, so `CC` variable is still ignored.
This is still needed:
```
--- a/make_cffi.py
+++ b/make_cffi.py
@@ -84,7 +84,7 @@
 # Distutils doesn't set compiler.preprocessor, so invoke the preprocessor
 # manually.
 if compiler.compiler_type == "unix":
-    args = list(compiler.executables["compiler"])
+    args = compiler.compiler
     args.extend(
         ["-E", "-DZSTD_STATIC_LINKING_ONLY", "-DZDICT_STATIC_LINKING_ONLY",]
     )
```
