### ISSUE TITLE
Throw a more correct exception for SEEK_END

### ISSUE THREAD

**Issue by octylFractal** [indygreg/python-zstandard#107]
In my opinion, throwing `ValueError` for `seek(n, SEEK_END)` on a `stream_reader` is incorrect. The [Python `io` docs](https://docs.python.org/3/library/io.html#io.IOBase.seek) say (for the `seek` method as a whole):
> Return `True` if the stream supports random access. If `False`, `seek()`, `tell()` and `truncate()` will raise OSError.

To me, this indicates that instead of throwing `ValueError`, `seek()` should throw an `OSError`. This would fix an issue with passing the `stream_reader` to `requests`' `data` parameter, which tries to read the length of a file-like object by issuing a `SEEK_END`, and catching `OSError` or `IOError` to indicate that it is unsupported. Source [here](https://github.com/psf/requests/blob/master/requests/utils.py#L150).

**Comment by octylFractal** [comment]
Alternatively, I see the comment in the relevant code:
> We /could/ support this with pos==0. But let's not do that until someone needs it.
This could be the time to add this support, as `pos==0` is exactly how requests does this. I'm not particularly partial to one way or the other.

**Comment by browdus** [comment]
To add a bit of supporting evidence for this, we ran into this exact issue in https://github.com/boto/boto3/issues/2555. This effectively means `stream_reader` can't be used directly with boto3's s3 `upload_fileobj` API because it attempts to probe for `SEEK_END` support, but gets an out-of-spec exception type.
