### ISSUE TITLE
Decompression fails if the compressed content is an empty bytestring

### ISSUE THREAD

**Issue by DanGoldbach** [indygreg/python-zstandard#11]
```
>>> zstd.ZstdDecompressor().decompress(zstd.ZstdCompressor(write_content_size=True).compress(b''))
ZstdError                                 Traceback (most recent call last)
<ipython-input-11-89c4c9bb5b8c> in <module>()
----> 1 zstd.ZstdDecompressor().decompress(zstd.ZstdCompressor(write_content_size=True).compress(b''))

ZstdError: input data invalid or missing content size in frame header
``` 

The cause is that there is no differentiation between a lack of a frame header and a frame header indicating content size = 0.

```
>>> zstd.ZstdCompressor(write_content_size=True).compress(b'') == zstd.ZstdCompressor(write_content_size=False).compress(b'')

True
```

Obviously this is a corner case, but one of the fundamental properties of a compression library should be that `decompress(compress(x)) == x` for all x.

**Comment by indygreg** [comment]
Thanks for the bug report.

My initial instinct is this is a bug in the Python bindings not flushing the header for an empty input (as opposed to a bug in the zstd library).

I'm away from my primary development machine for a few days. I'll try to look into this as early as Wednesday of next week.

**Comment by indygreg** [comment]
This is a bug in the Python bindings. `ZSTD_getDecompressedSize()` returns `0` when the content size header is missing and when the content size is 0. The current code assumes only the former is possible.

I'll try to have a fix shortly.

**Comment by indygreg** [comment]
According to upstream, this is a deficiency in the current C API. When writing content sizes to the output frame, there's no C API to decompress to distinguish between "no content size" and "content size of 0."

Until this is fixed upstream, I'm inclined to have the Python bindings raise an exception if trying to compress the empty buffer when writing content sizes. We can allow an argument to override the default behavior if people insist on footgunning themselves.

**Comment by DanGoldbach** [comment]
This sounds like a suitable temporary solution to tie us over until upstream fixes it properly.
