### ISSUE TITLE
zstd shared library conflicts with other packages

### ISSUE THREAD

**Issue by tpwrules** [indygreg/python-zstandard#115]
The library file `zstd.cpython-38-x86_64-linux-gnu.so` (on my Python 3.8 Linux PC) is installed globally in site-packages instead of in the `zstandard/` package directory. This means it can conflict with other packages which install something similar.

In particular, it conflicts with the `zstd` Python package, which installs its library to the same file. Because `zstandard` vendors its own version of zstd, the library should be moved into `zstandard/` with the rest of the package.

**Comment by indygreg** [comment]
Yes, the names of the modules are an historical oddity. Everything should be in the `zstandard` package.
