### ISSUE TITLE
how to override "cc" provided by distutils inside make_cffi

### ISSUE THREAD

**Issue by dkonst13** [indygreg/python-zstandard#117]
Hello, 

I am trying to build py-zstandard 0.14.0 on Centos8 using gcc 9.3.0 built locally, no system gcc installed, with locally built Python 3.7.16 and cffi-1.12.2

The build fails. The distuilts returns "cc" compiler while it is not avaialble in GNU gcc installation.

Is there anyway override it not applying ugly fix - creation of "cc" symlink pointing to "gcc"

Kind Regards,
       Dmitri

**Comment by indygreg** [comment]
This should be fixed as of 0d1329ab426dde7dc319905da0656cd44db41988.
