### ISSUE TITLE
This code can be removed

### ISSUE THREAD

**Issue by animalize** [indygreg/python-zstandard#124]
```c
 if (!PyBuffer_IsContiguous(&dest, 'C') || dest.ndim > 1) {
	PyErr_SetString(PyExc_ValueError,
	                "destination buffer should be contiguous and have at most one dimension");
	goto finally;
}
```

In `PyArg_ParseTuple*()` functions, the first condition has been checked.
`w*`:
    https://github.com/python/cpython/blob/v3.5.0/Python/getargs.c#L1251
`y*`:
    https://github.com/python/cpython/blob/v3.5.0/Python/getargs.c#L857
    https://github.com/python/cpython/blob/v3.5.0/Python/getargs.c#L1306

The second condition is rare, even in Python's [Argument Clinic](https://docs.python.org/3.9/howto/clinic.html), it is not checked for bytes-like object:
https://github.com/python/cpython/blob/3.9/Modules/clinic/_lzmamodule.c.h#L28-L34

**Comment by indygreg** [comment]
Good catch! I agree we can remove these extra checks.

The `ndim` bit is likely semantically correct. But very little code in the wild looks for this. FWIW the only code I know actually setting multiple dimensions in a PyBuffer is NumPy.
