### ISSUE TITLE
#include <sys/types.h> should be before #include <sys/sysctl.h>

### ISSUE THREAD

**Issue by yurivict** [indygreg/python-zstandard#128]
Here: https://github.com/indygreg/python-zstandard/blob/main/c-ext/backend_c.c#L16

The manpage sysctl(3) says:
```
SYNOPSIS
     #include <sys/types.h>
     #include <sys/sysctl.h>

     int
     sysctl(const int *name, u_int namelen, void *oldp, size_t *oldlenp,
         const void *newp, size_t newlen);
```

**Comment by indygreg** [comment]
Fun fact: this was originally the case but the order was changed as part of running `clang-format` on the code base and I missed that as part of the massive diff of running `clang-format`.

I'll revert this change and get a fix in for 0.15.1.

Thanks for the report.
