### ISSUE TITLE
zstandard conda-forge feedstock not being updated 

### ISSUE THREAD

**Issue by lr4d** [indygreg/python-zstandard#134]
zstandard is at 0.14.1 on [conda-forge](https://anaconda.org/conda-forge/zstandard), while it's at 0.15.1 on [pypi](https://pypi.org/project/zstandard/)

It looks like the feedstock is not being updated due to some CI failures: https://github.com/conda-forge/zstandard-feedstock/pull/32

**Comment by xhochy** [comment]
This is fixed, I'm always happy for help on the feedstock!

**Comment by lr4d** [comment]
Thanks, @xhochy . I'll see if I can remind myself to look into that a bit deeper next time so that you don't always need to do it
