### ISSUE TITLE
Python 2.7.12 test errors with CFFI

### ISSUE THREAD

**Issue by terrelln** [indygreg/python-zstandard#15]
There are 53 tests that error with python 2.7.12: https://gist.github.com/terrelln/c76ad7d6034f8f5bbf0e8575c5f11321

```
======================================================================
ERROR: test_write_size_cffi (tests.test_decompressor.TestDecompressor_write_to)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/terrelln/repos/python-zstandard/tests/test_decompressor.py", line 294, in test_write_size
    decompressor.write(c)
  File "/Users/terrelln/repos/python-zstandard/zstd_cffi.py", line 931, in write
    data_buffer = ffi.from_buffer(data)
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode object

----------------------------------------------------------------------
```

**Comment by indygreg** [comment]
This is only occurring with CFFI. And, I can't reproduce this with 2.7.12 + CFFI 1.9.1 on 64-bit Linux.

Can you confirm you are running the latest cffi and pycparser packages (1.9.1 and 2.17)?

**Comment by terrelln** [comment]
Thanks for the help! I upgraded to the latest cffi and everything passed.

**Comment by indygreg** [comment]
Great!

Out of curiosity, which version of cffi were you using? I'd like to narrow down which version is required so I can set the version dependency in `setup.py`.

**Comment by indygreg** [comment]
Nevermind - it looks like http://cffi.readthedocs.io/en/latest/whatsnew.html#v1-8 addressed this.
