### ISSUE TITLE
How can I stream a file that says "Frame requires too much memory" ?

### ISSUE THREAD

**Issue by rhaksw** [indygreg/python-zstandard#157]
Hi, I have a highly compressed file that I'd like to stream. When I use [this code](https://github.com/reveddit/ragger/blob/973b487d2cdb244d3b3fcbb059c8cece9e8547c1/pushshift_file_reader_writer.py#L69) it says,

```
    chunk = reader.read(zst_num_bytes)
zstd.ZstdError: zstd decompress error: Frame requires too much memory for decoding
```

For other files that are not so highly compressed this code works fine. Also, I am able to decompress the file on the command line with `zstd --long=31 -d file.zst`. I discovered this parameter from the error,

```
file.zst : Decoding error (36) : Frame requires too much memory for decoding 
file.zst : Window size larger than maximum : 2147483648 > 134217728
file.zst : Use --long=31 or --memory=2048MB
```

Is there some equivalent to `--long` (which changes `windowLog`) within zstandard? I see that `ZstdCompressionParameters` accepts a `window_log` parameter, however `ZstdCompressionParameters` can only be supplied to `ZstdCompressor`.

[Searching google](https://www.google.com/search?q=python+%22Frame+requires+too+much+memory+for+decoding%22), I see it in the documentation for [pyzstd here](https://pyzstd.readthedocs.io/en/latest/#DParameter.windowLogMax). I'm hoping I can avoid changing my code to work with that package since it seems to work differently than what I have setup.

Thanks!

**Comment by rhaksw** [comment]
I got it working by setting `max_window_size`,

`ZstdDecompressor(max_window_size=2147483648)`

I had tried adjusting that parameter before but I must have set it too high or too low. Simply taking the value from the command line tool's error works.

**Comment by hardianlawi** [comment]
Could we reopen this issue? I'm having similar issue and setting `max_window_size= 2147483648` caused memory leak.

I could stream it by running a command like `zstd -cdq file.zst --long=31 | ./python_program.py` but it would be nice if I could do everything in a single python script.

Thank you. I would appreciate the help here. 🙏🏼  @indygreg

**Comment by hardianlawi** [comment]
Thanks for the super clear explanation @indygreg

**Comment by tvalentyn** [comment]
The documentation on https://python-zstandard.readthedocs.io/en/latest/decompressor.html says max_window_size is measured in kibibytes. Is it indeed kibibytes and not bytes?
