### ISSUE TITLE
Allow setting the Frame size after writes are complete

### ISSUE THREAD

**Issue by cbenning** [indygreg/python-zstandard#158]
I have a use-case where I write bytes to a stream until a specific size is exceeded then I stop. I don't know how many bytes I will write until I am done. Is there a way to expose lib.ZSTD_CCtx_setPledgedSrcSize in the ZstdCompressionWriter class so that I can set the data size after writing but before flushing the frame? Or perhaps an optional parameter for flush() that lets you set the size there? 

Thanks for your time.

**Comment by indygreg** [comment]
The frame content size is written in the zstd frame *header* (https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md). So if you are streaming output and have already written the frame header, there's no way to retroactively go back and set the frame size.

If you are actually streaming, leaving the frame size as undefined should be fine. But if you insist on writing it in the included zstd frame, you'll need to buffer incoming data first (to know its final size) then perform a new compression operation, specifying that now known size.

Does that make sense?

**Comment by cbenning** [comment]
Makes sense. In my case I can't do that either because I'm trying to keep the total compressed size below but as close as possible to a limit, so I'm not sure how much data I'll be trying to jam in until I've already compressed it. The problem I've had is that when decompressing (without the streaming interface) I get the exception "could not determine content size in frame header" but setting max_output_size solves it so I'll just need to try and guess a max size with lots of headroom and set it.
