### ISSUE TITLE
No `unused_data` in ZstdDecompressionObj

### ISSUE THREAD

**Issue by sfan5** [indygreg/python-zstandard#161]
The documentation says:
> This type implements a compressor that conforms to the API by other decompressors in Python’s standard library.

However looking at https://github.com/indygreg/python-zstandard/blob/main/rust-ext/src/decompressionobj.rs, no attempt is made to handle unused data or provide the [`unused_data` attribute](https://docs.python.org/3/library/zlib.html#zlib.Decompress.unused_data) that both zlib and bz2 do provide with their compression objects.

Somewhat related it's also unclear to me whether ZstdDecompressionObj reads across zstd frames or not. Because I needed the behavior of only reading a single compressed blob and leaving the rest alone (just like `zlib.decompressobj`...) I ended up using `ZstdDecompressor.stream_reader` which has an explicit parameter to control this behavior.

**Comment by indygreg** [comment]
I agree that we should provide the `unused_data` attribute for compatibility with the stdlib types.

**Comment by pquentin** [comment]
Hello! For what it's worth, this issue is currently preventing us from adopting `python-zstandard` in urllib3, see https://github.com/urllib3/urllib3/pull/2624#issuecomment-1149975331 for details.

**Comment by indygreg** [comment]
Thanks for letting me know about the urllib3 dependency, @pquentin!

urllib3 is an important package in the Python ecosystem and I'll try to get this implemented to unblock urllib3.

**Comment by indygreg** [comment]
I've implemented `unused_data` on `main`. But GitHub Actions isn't running the macOS jobs at the moment (I'm not sure why), so I can't fully test and release at the moment. Maybe tomorrow...

**Comment by indygreg** [comment]
I just published 0.18.0 to PyPI.
