### ISSUE TITLE
Check type of cctx/dctx

### ISSUE THREAD

**Issue by jonashaag** [indygreg/python-zstandard#162]
```py
import zstandard as zstd

zstd.open("x.zst", mode="wb").write(b"x")
print(zstd.open("x.zst", mode="rb").read())
print(zstd.open("x.zst", mode="rb", dctx=zstd.ZstdCompressor()).read())
```

Note the typo in the `dctx` argument. The result of `.read()` will be the contents of `x.zst` compressed again, rather than decompressed contents. IMO we should be checking the type of `dctx` and `cctx` here to prevent this misuse.

**Comment by indygreg** [comment]
When I read this report, my initial instinct was to implement the type checking. However, I'm not convinced we should.

There are multiple backends that can implement `ZstdCompressor()` and that means the Python types are distinct. So a simple `isinstance()` check here would prevent utilizing the non-default backend with `zstd.open()`. To fix this, we'd have to define a common base type and have all the backends inherit from it. This results in a lot of code bloat for minimal gain.

Python is duck typed. I think that if you want stronger type checking, you should use a type checker like mypy. This package provides a `zstandard/__init__.pyi` file defining type annotations. So if a type checker is used, it should properly detect the incorrect type and prevent the bug you reported.

So I'm closing this as won't fix.
