### ISSUE TITLE
Question about thread safety and/or documentation suggestion

### ISSUE THREAD

**Issue by dsedivec** [indygreg/python-zstandard#166]
The documentation for thread safety says not to use the same `ZstdCompressor`/`ZstdDecompressor` from multiple threads.  It does not *explicitly* mention the thread safety of objects such as `ZstdCompressor`/`ZstdDecompressor`, but scanning the implementation very (_very_) quickly, I'm guessing classes such as `ZstdCompressionReader` are also not thread safe.  Is that correct?

If yes, I humbly suggest that the documentation be specific on this point.  Perhaps all it takes is something like this in `api_usage.md` (addition in italics):

> Do not operate on the same `ZstdCompressor` and `ZstdDecompressor` instance simultaneously from different threads.  *Objects returned by `ZstdCompressor` and `ZstdDecompressor`, such as instances of `ZstdCompressionReader` and `ZstdDecompressionReader`, must likewise be used only from a single thread at a time.*

*EDIT:* Conversely, if I'm wrong and the file-like objects *are* thread safe, that might be equally valuable to explicitly document.

Thank you for your work on this library!  It's very complete and very useful.

**Comment by indygreg** [comment]
Under the hood, objects derived from `ZstdCompressor` / `ZstdDecompressor` like `ZstdCompressionReader` operate against the shared context bound to the `ZstdCompressor` / `ZstdDecompressor` instance. They therefore inherit the thread unsafety of their original values.

I'll tweak the docs to make this clearer. Thank you for pointing out this ambiguity.
