### ISSUE TITLE
Update bundled copy of zstd to 1.5.4

### ISSUE THREAD

**Issue by thesamesam** [indygreg/python-zstandard#190]
Please upgrade the vendored copy of zstd at https://github.com/indygreg/python-zstandard/tree/main/zstd to 1.5.4. Thanks!

**Comment by marxin** [comment]
Thank you for the fix. Are you planning to do a release soon? OR should I rather cherry-pick the change?

**Comment by indygreg** [comment]
I'm planning to release 0.20 in the next ~30 minutes assuming CI comes back green.

**Comment by indygreg** [comment]
0.20.0 is published to PyPI. Took longer than anticipated because GitHub Actions only gives you so many macOS runners concurrently.

**Comment by mgorny** [comment]
Thank you!
