### ISSUE TITLE
Suppory for zstd v1.5.5

### ISSUE THREAD

**Issue by gaby** [indygreg/python-zstandard#192]
@indygreg Zstd v1.5.5 was released recently, can you add support for this version?

Thanks!

**Comment by dc0** [comment]
Seconding the request. According to the 1.5.5 changelog at [https://github.com/facebook/zstd/releases](https://github.com/facebook/zstd/releases) the previous version has a data corruption bug, so it would be good to get the fix in python-zstandard as well.
