### ISSUE TITLE
Add support for musllinux wheels

### ISSUE THREAD

**Issue by jdholtz** [indygreg/python-zstandard#193]
Hi! I want to be able to build `zstandard` on Alpine Linux (for Docker containers) without needing to install the necessary build tools. Currently, building from source takes about 5 minutes for me (and increases the size of the container). It would be great if you could make musllinux wheels to support `x86_64`, `aarch64`, and `armv7l`. Thanks!

**Comment by indygreg** [comment]
I published musllinux x86_64 and aarch64 wheels in the 0.22.0 release made a few minutes ago. I'll file a separate issue for armv7l arch wheels.

**Comment by jdholtz** [comment]
Thank you very much!
