### ISSUE TITLE
ZstdDecompressorIterator stops before frame is fully decompressed

### ISSUE THREAD

**Issue by csfoo** [indygreg/python-zstandard#2]
Thanks for this very useful library!

I encountered an issue with decompression using the streaming decompressor iterator `read_from` where the iterator would raise `StopIteration` before reading to the end of the file. The file is however successfully decompressed with the zstd command line utility from the official repo. (I would include the file but it is really big.)

I think this behaviour is due to the following code:
https://github.com/indygreg/python-zstandard/blob/master/zstd.c#L2260

`zresult == 1` does not necessarily imply that we are done with the input. It could also reflect that an additional byte needs to be read (as in my case), or more generally, that there's more to be done (this is reflected in the [updated documentation in the master branch of zstd](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L261)).

Removing this conditional assignment allows for the entire file to be decompressed; I think the code correctly handles the case where the buffers are not flushed but it is done reading the input. 

That said I'm wondering if running out of input before the output is properly flushed should raise an exception instead of `StopIteration`.

**Comment by indygreg** [comment]
Thanks for the great bug report. I blame the bad upstream docs :)

I'll try to get a fix out today. I really wish I were able to reproduce this though. I do have some fuzzing tests verifying round tripping compression and decompression. Hopefully they'll be able to find a reproduce case.

**Comment by indygreg** [comment]
I think I fixed this in 6d3bed4. In the process of uploading 0.3.3 to PyPI now.

Thanks again for the great bug report.
