### ISSUE TITLE
Changelog for 0.21.0?

### ISSUE THREAD

**Issue by wimglenn** [indygreg/python-zstandard#203]
Hi, where can I find the changes since 0.20.0?
They're not on https://github.com/indygreg/python-zstandard/releases
https://github.com/indygreg/python-zstandard/compare/0.20.0...0.21.0

**Comment by indygreg** [comment]
I forgot to create the GitHub release when I published 0.21.0 to PyPI. I retroactively created it today.

The release notes are always in the `docs/news.rst` file.

**Comment by wimglenn** [comment]
@indygreg  Thank you for that!  By the way, I've just bumped my (Python 3.12) app's dependencies from python-zstandard 0.21.0 (sdist installation) to 0.22.0 (wheel installation) and everything continues working smoothly. So even though the switch to `pyproject.toml` was laborious, your end result looks good.
