### ISSUE TITLE
Does the implementation release GIL?

### ISSUE THREAD

**Issue by yuri-kilochek** [indygreg/python-zstandard#208]
Specifically, I want to dispatch calls to `ZstdCompressor.compress`/`ZstdDecomrpessor.decompress` onto a thread pool from `async` code to not block the even loop. The internal multithreading support isn't helpful for this use case.

**Comment by indygreg** [comment]
Yes, the GIL should be released for all compression/decompression APIs. You can audit the source code to confirm. e.g. https://github.com/indygreg/python-zstandard/blob/1dc0596ccce5a3e84467183b35aaab96e445a047/c-ext/compressor.c#L549
