### ISSUE TITLE
ZstdDecompressor.stream_reader is not found anymore

### ISSUE THREAD

**Issue by selevit** [indygreg/python-zstandard#25]
I'm using `zstandard==0.8.1`.

`ZstdCompressor.stream_reader` method is not found but it's described in docs.
There is a` read_from` method which returns an iterator but it's not documented.

It will be nice to keep docs actual :)

**Comment by indygreg** [comment]
The stream reader API is in the not-yet-released 0.9 release. If you got it from running `pip install zstandard==0.8.1`, then we accidentally packaged a pre-release on PyPI. Can you confirm you are actually running 0.8.1 and not a pre-release?

**Comment by void-dragon** [comment]
yes, indeed. i can confirm this.
python 3.6.3
pip install zstandard==0.8.1

**Comment by indygreg** [comment]
As I said, the stream reader API is not yet in a published release. If you want to read the docs for 0.8.1, go to https://github.com/indygreg/python-zstandard/blob/b3a8f1a7f5b3a791a1d9fed372d2b0d63fb66290/README.rst.
