### ISSUE TITLE
Move away from ZSTDMT

### ISSUE THREAD

**Issue by terrelln** [indygreg/python-zstandard#32]
The `ZSTDMT` API is superseded by the new advanced API and eventually all the functions will be made `static`. We will keep the `ZSTDMT` around for a few releases to give people time to update. The new advanced API is capable of multithreading, and supports the magicless format.

**Comment by indygreg** [comment]
I plan on porting the code to the new advanced API... sometime. Hopefully for the 0.9 release.

**Comment by indygreg** [comment]
`master` is now using the new advanced API. It will be part of the `0.9` release.

FWIW, I *really* like the new advanced API! I can't wait for the decompression side to be implemented. I see that's going to be part of zstd 1.3.4. I may hold off releasing `0.9` until 1.3.4 is released so everything is using the advanced APIs.

**Comment by terrelln** [comment]
We are planning on releasing 1.3.4 this week, probably today.

**Comment by terrelln** [comment]
We just released 1.3.4.
