### ISSUE TITLE
upload zstandard to conda

### ISSUE THREAD

**Issue by talkaminker** [indygreg/python-zstandard#4]
This will be great (or conda-forge)
you said in the email I should tell you if you forget

**Comment by indygreg** [comment]
I've added CI to generate Conda packages. I've uploaded some packages to https://anaconda.org/indygreg/zstandard.

I've never uploaded Conda packages before. So please let me know if this is insufficient. Please be specific with what is needed to better support Conda.

Also, sorry for the delay. I was out of town for a few weeks.
