### ISSUE TITLE
copy_stream leaks memory (when compressing)

### ISSUE THREAD

**Issue by talkaminker** [indygreg/python-zstandard#40]
Same as [https://github.com/indygreg/python-zstandard/issues/35](url)
copy_steam leaks also on compression
copy_stream leaks a lot of memory when compressing.
The amount leaked seems to be proportional to the size of the input stream
changing `1024*1024` to `1024 ` leaks less memory 
```
import os
import gc
import zstd
import tempfile
import resource

with tempfile.NamedTemporaryFile('wb', delete=False) as f:
    f.write(os.urandom(1024*1024))
input_path = f.name
f = tempfile.NamedTemporaryFile(delete=False); f.close()
output_path = f.name
for i in range(1001):
    with open(input_path, 'rb') as ifh, open(output_path, 'wb') as ofh:
        zstd.ZstdCompressor().copy_stream(ifh, ofh)
    if i % 100 == 0:
        print(i, resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
        gc.collect()
os.remove(input_path)
os.remove(output_path)
```

output:
0 12952
100 116052
200 219148
300 322460
400 425780
500 529092
600 632404
700 735716
800 839036
900 942348
1000 1045660

**Comment by vhavel** [comment]
When can we expect the fix (i.e. v0.8.2) to be released into pypi? Thanks!

**Comment by indygreg** [comment]
0.8.2 was just released to PyPI.
