### ISSUE TITLE
Linux and macOS wheels

### ISSUE THREAD

**Issue by thewtex** [indygreg/python-zstandard#41]
Thanks for putting this package together!

Before depending on it, I would like for there to be Linux and macOS binary wheels on PyPI.

Would a PR be accepted that improves the build system to generate Linux and macOS wheels with [scikit-build](https://scikit-build.readthedocs.io/)?

CC: @jcfr

**Comment by indygreg** [comment]
Yes, I would accept a PR to generate Linux and macOS wheels.

Although, I'm not sure about `scikit-build`. I'm going to say that can't be a required dependency to run `setup.py`. If it were optional I'd be OK with it. I'm fine with it being required to build Linux and macOS wheels. Although if a solution for building Linux and macOS wheels without `scikit-build` comes around, I'd take that patch. (I'm just not sure what `scikit-build` brings to the table and I don't like taking dependencies unless they are truly needed.)

**Comment by thewtex** [comment]
`scikit-build` brings better support for robustly building on more platforms and architectures, cross-compilation support, and better support for system introspection, i.e. when someone tries to create a Linux, Homebrew, or Anaconda package for python-zstandard, the build will be able to find and use the zstandard library distributed by the package manager.

When you use `scikit-build`, it is easier to create binary wheels, in which case people don't have to build from source at all ;-).

I will see if I can forgo `scikit-build` for now and just create wheels for Linux and macOS.
