### ISSUE TITLE
--system-zstd fails: error: unknown type name 'ZSTD_dictContentType_e'

### ISSUE THREAD

**Issue by yurivict** [indygreg/python-zstandard#43]
Trying to build 0.9.0 with ```--system-zstd``` fails:
```
In file included from /usr/ports/archivers/py-zstandard/work-py27/zstandard-0.9.0/c-ext/decompressionreader.c:9:
/usr/ports/archivers/py-zstandard/work-py27/zstandard-0.9.0/c-ext/python-zstandard.h:86:2: error: unknown type name 'ZSTD_dictContentType_e'
        ZSTD_dictContentType_e dictType;
        ^
```

**Comment by indygreg** [comment]
It needs zstandard 1.3.4 to build. I could probably add some preprocessor checks to make this clearer.

Making the Python features conditional and usable with an older zstandard library would be a bit more difficult.

**Comment by yurivict** [comment]
I see now that it was a version mismatch.
It works now, thanks!
