### ISSUE TITLE
Would you please add simple examples to the README?

### ISSUE THREAD

**Issue by aadler** [indygreg/python-zstandard#45]
Would you add simple examples to the README, please? I'm still unsure how to properly invoke zstandard to compress a file using Python. Thank you.

**Comment by enugentdt** [comment]
The readme (not sure if it's after your issue or before) has a simple example here:

https://github.com/indygreg/python-zstandard#simple-api

Do note that this API is prone to abuse, as `The input and output values must fit in memory, so passing in very large values can result in excessive memory usage. For this reason, one of the streaming based APIs is preferred for larger values.`

**Comment by aadler** [comment]
Yes, that's good enough for now. Thanks!
