### ISSUE TITLE
Is it possible to relax `with` usage requirements?

### ISSUE THREAD

**Issue by gwk** [indygreg/python-zstandard#57]
First of all, thank you for all of the work that went into publishing this package. I have been experimenting with it and would very much like to incorporate it into my work. However, I find that the requirement to only read from the decompressor inside of a `with` statement is somewhat inconvenient for use in cpython data processing scripts. I understand that it is a best practice to open a file within a `with` context. However it is not a requirement for correctly using other file handles and decompressor handles. As a result I have existing code for which Zstandard does not easily drop in as a replacement for gzip or lzma/xz.

I am curious if there is a strong technical requirement that the decompressor must be used in this fashion, or if it is merely the library enforcing the best practice. If the latter, please consider relaxing the requirement so that the decompressor handle can be read from and then closed with out the use of `with`. Thank you!

**Comment by indygreg** [comment]
The upcoming 0.10 release will drop the `with` requirement for the `stream_reader()` interfaces. This was tracked by #34.

And I think it makes sense to loosen the requirement on other APIs as well. Is there a particular API you would like the requirement dropped from? (Some are easier to change than others.)

**Comment by gwk** [comment]
My use case is that I have a generic load function that takes a file path and dispatches based on file extension. It handles both data formats (.json, .csv, etc) and compression formats, (.gz, .zst, etc). The more completely the zst decompressor behaves like io.RawIOBase, the better! Looking forward to testing the new release.

**Comment by gwk** [comment]
@indygreg I'm coming back to this, and finding that I would also benefit from dropping the `with` requirement for `stream_writer`. The use case is to create a file-like object that I can write uncompressed input data to, and will result in a zst compressed file.  Is this possible? Thanks again, -g

**Comment by gwk** [comment]
In case you are curious, the exact use case is that I am opening writeable files lazily and holding them in a dictionary, one per year as data records stream in. I then dispatch to the appropriate file handle to write records out in the appropriate year, and then manually close each one at the end. I don't see any way of accomplishing this given the stream_writer requirement to use `with`.
