### ISSUE TITLE
`ZstdDecompressionReader.closed` should be a property, not method.

### ISSUE THREAD

**Issue by gwk** [indygreg/python-zstandard#58]
`IOBase` defines `closed` as a property, and the builtin decompressors types for gz and lzma/xz follow this API. It would be great if Zstandard could match that; as it is, when you try to create a TextIOWrapper with a `ZstdDecompressionReader`, the read fails with "ValueError: I/O operation on closed file.", because the `closed` method evaluates to `True`.

**Comment by indygreg** [comment]
This will be fixed in 0.10.1.
