### ISSUE TITLE
Saving and loading the training dict_data

### ISSUE THREAD

**Issue by djih** [indygreg/python-zstandard#6]
After we train on a sample, we want to be able to save the dict_data to a binary file so we can load and re-use it across different applications. It seems like the ZstdCompressionDict object is not pickle-able or serializable. We don't want to have to re-train on a sample every time we want to use zstd.

My current work-around is to use the zstd command line tool to generate the dictionary binary, and then load it into python. The issue with that is the command line program has its own limitations, such as this: https://github.com/facebook/zstd/issues/373#issuecomment-259847707

**Comment by indygreg** [comment]
Thanks for the feature request. I can't believe I forgot to implement a way to get data out of the instance!

This is now implemented in master. I plan on cutting a new release shortly. This will be in it.
