### ISSUE TITLE
Would  it be possible to upgrade to zstd-1.3.8 ?

### ISSUE THREAD

**Issue by stonebig** [indygreg/python-zstandard#67]

**Comment by indygreg** [comment]
Definitely. (I didn't even realize 1.3.8 was released!)

I'll do this upgrade the next time I sit down to hack on python-zstandard. I'm not sure when that will be, however.

There's a "donate" link at the bottom of the README that can be used to give me a financial incentive to do that sooner :)

**Comment by indygreg** [comment]
I have pushed a `zstd-1.3.8` branch that appears to be mostly working with 1.3.8. I'm recovering from a nasty head cold and will defer merging that branch until I'm feeling better. But 1.3.8 should be part of the eventual 0.11 release.

**Comment by stonebig** [comment]
Thanks for the update, have a nice recovery.

**Comment by indygreg** [comment]
I just pushed 1.3.8 to the master branch.
