### ISSUE TITLE
zstandard 0.10.2 does not install on Debian 8 "Jessie" with Python 2

### ISSUE THREAD

**Issue by windsurfer1122** [indygreg/python-zstandard#68]
Here's the error log:
```
# pip2 install zstandard
Downloading/unpacking zstandard
  Downloading zstandard-0.10.2.tar.gz (611kB): 611kB downloaded
  Running setup.py (path:/tmp/pip-build-iHDlBF/zstandard/setup.py) egg_info for package zstandard
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-iHDlBF/zstandard/setup.py", line 50, in <module>
        import make_cffi
      File "make_cffi.py", line 154, in <module>
        ffi.set_source('_zstd_cffi', '''
    AttributeError: 'FFI' object has no attribute 'set_source'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-iHDlBF/zstandard/setup.py", line 50, in <module>

    import make_cffi

  File "make_cffi.py", line 154, in <module>

    ffi.set_source('_zstd_cffi', '''

AttributeError: 'FFI' object has no attribute 'set_source'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-iHDlBF/zstandard
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-iHDlBF/zstandard
```

Package `python-dev` is installed

**Comment by indygreg** [comment]
I'm not sure how this could be. I don't see anything in the cffi changelog about adding/removing the `set_source` function. Is it possible you are building with a Debian python-cffi package and that package was somehow modified to not have a `set_source()`?

Can you try creating an empty virtualenv and see if building works in it? That should rule out the system Python install being wonky. You can run `pip install -r ci/requirements.txt` to populate the virtualenv with a requirements file in this repository. Or just copy the file from https://raw.githubusercontent.com/indygreg/python-zstandard/1a904bc8c76a86832f3083eb42e9831f5f4cb320/ci/requirements.txt.

**Comment by windsurfer1122** [comment]
Same failure on a clean Debian 8 "Jessie" VM with additional `apt-get install python-pip python-dev`

```
# pip2 -V
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
# pip2 list
argparse (1.2.1)
cffi (0.8.6)
chardet (2.3.0)
colorama (0.3.2)
cryptography (0.6.1)
defusedxml (0.4.1)
docutils (0.12)
html5lib (0.999)
ndg-httpsclient (0.3.2)
Pillow (2.6.1)
pip (1.5.6)
ply (3.4)
pyasn1 (0.1.7)
pycparser (2.10)
Pygments (2.0.1)
pyOpenSSL (0.14)
python-apt (0.9.3.11)
python-debian (0.1.27)
python-debianbts (1.11)
reportbug (6.6.3)
requests (2.4.3)
roman (2.0.0)
setuptools (5.5.1)
six (1.8.0)
SOAPpy (0.12.22)
urllib3 (1.9.1)
wheel (0.24.0)
wsgiref (0.1.2)
wstools (0.4.3)
```

**Comment by windsurfer1122** [comment]
My workaround/solution is the following adopted from https://pip.pypa.io/en/stable/installing/

```
apt--get purge python-pip python-dev
apt-get autoremove
wget https://bootstrap.pypa.io/get-pip.py
python2 get-pip.py
pip2 install zstandard
```

With newer pip it installs fine.

**Comment by indygreg** [comment]
cffi 0.8.6 is ancient. And `setup.py` sets an `install_requires` to require a newer CFFI. But I guess the problem is the CFFI code is running as part of `setup.py` *before* the call to `setup()` and the CFFI version check never has the chance to run and prevent the install.

Why a newer pip fixes things, I'm not sure. We may want to tweak the `setup.py` logic so it does its own version sniffing of the imported cffi and skips if the version is too old. Alternatively, we can integrate the cffi build actions into a proper distutils build step. That's how you are arguably supposed to do things in `setup.py` files. But it is a bit harder to do things this way and people avoid it in practice. I like the simple solution of implementing crude version checking so the failure mode is more friendly.
