### ISSUE TITLE
Exception raised while initializing ZstdCompressor on PyPy 5.8.0

### ISSUE THREAD

**Issue by thedrow** [indygreg/python-zstandard#69]
I'm getting the following exception while testing zstdandard with PyPy 5.8.0:
```
TypeError: gc() got an unexpected keyword argument 'size'
```

You can see the full traceback at https://travis-ci.org/celery/kombu/jobs/477482010#L600

Is there a minimum PyPy version we support?
I don't see us testing this library on PyPy during builds. Should we add them?

**Comment by indygreg** [comment]
I'm not sure about PyPy requirements. I thought things "just worked."

We should definitely add PyPy test coverage to CI. If you submit a PR, the Travis and AppVeyor CI should run automatically for that PR. Otherwise I'll look into adding PyPy coverage the next time I sit down to hack on python-zstandard.

**Comment by thedrow** [comment]
I'm not sure I understand your CI process.

**Comment by indygreg** [comment]
We hard require CFFI 1.11. PyPy ships CFFI. So you'll need to use a PyPy with a modern enough CFFI. It might also be possible to upgrade the CFFI in a PyPy distribution, possibly by using a virtualenv.

As of commit b148e91, `setup.py` will now automatically disable CFFI if the installed CFFI is too old. This should hopefully prevent weird error messages at run-time.

There is potentially room to only require CFFI 1.10. However, that is probably the lowest we can do, as we need 1.10's support to properly recognize certain types as buffers. Please file a new issue if the PyPy CFFI version story is so bad that the current minimum version requirements are too painful.

**Comment by thedrow** [comment]
They are fine by me. The only thing I wanted is to define our minimum required PyPy version.
