### ISSUE TITLE
0.5.0 tarball on PyPI is missing setup_zstd.py

### ISSUE THREAD

**Issue by codeman38** [indygreg/python-zstandard#7]
The 0.5.0 tarball which was just uploaded to https://pypi.python.org/pypi/zstandard is missing the `setup_zstd.py` source file which is imported by setup.py. As a result, running `pip install zstandard` produces the following error:

```
Collecting zstandard
  Using cached zstandard-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NfA1pg/zstandard/setup.py", line 15, in <module>
        import setup_zstd
    ImportError: No module named setup_zstd

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NfA1pg/zstandard/
```

**Comment by indygreg** [comment]
Ugh. I just created a 0.5.1 release and should have the 0.5.1 files uploaded to PyPI in a few minutes. Thanks for reporting the issue. I should have tested that things install correctly from PyPI :/

**Comment by indygreg** [comment]
And there were source distribution issues with 0.5.1. 0.5.2 being built now.
