### ISSUE TITLE
Streaming decompressor broken

### ISSUE THREAD

**Issue by huguesb** [indygreg/python-zstandard#75]
A compressed file created with the streaming compressor is successfully decompressed by the `zstd` command line:

```
zstdcat tmp.msg.zst | hexdump | head
0000000 8a c4 12 6e 61 6d 65 64 5f 74 72 61 6e 73 66 6f
```

However, reading it with the streaming decompressor as follows:
```
        ccxt = zstd.ZstdCompressor()
        with ccxt.stream_reader(open('tmp.msg.zst', 'rb')) as f:
            print (f.read(16).encode('hex'))
```

yields complete garbage:
```
28b52ffd005000001028b52ffd00503c
```

**Comment by indygreg** [comment]
I think the problem is that you are using a `ZstdCompressor` instead of `ZstdDecompressor`. So when you `read()` you are obtaining the compressed output of a given file.

(`\x28\xb5\x2f\xfd` is the 4 byte zstd frame header by the way. If you see that sequence of bytes, you have zstd data.)

**Comment by huguesb** [comment]
Oops, you're right, I feel silly.
