### ISSUE TITLE
Stream writer memory usage dependent on how many bytes written

### ISSUE THREAD

**Issue by tomerz90** [indygreg/python-zstandard#77]
Im not sure if its by design (couldnt find anything online) but it seems the memory usage for of the stream writer increase as you write more bytes through,which seems odd to me since compression stream usually keep fixed size buffers, is this a memory leak?

Code:
```
 from zstandard import ZstdCompressor as zs
 import uuid
 from contextlib import ExitStack
 
 with ExitStack() as stack:
     for i in range(600):
         ctx = zs(threads=-1)
         ff = stack.enter_context(open(str(i), 'wb'))
         context = stack.enter_context(ctx.stream_writer(ff))
         hashes = 100000
         for j in range(hashes):
             context.write(str(uuid.uuid4()).encode())
         # context.flush()
```
I tried with and without flush, same results.
As you increase `hashes`, the memory usage increases (as viewed in `top` and using the `memory_size` function), `memory_size` shows that the size is ~3.5MB.

**Comment by romange** [comment]
@tomerz90  did you try using threads=0 ?

**Comment by tomerz90** [comment]
Yes, same results
