### ISSUE TITLE
class ZstdDecompressor not seen

### ISSUE THREAD

**Issue by nprashan** [indygreg/python-zstandard#8]
Hi,

I am not able to see ZstdDecompressor class in the code. Shouldn't it be as part of zstd_cffi.py ?
Or am I missing something?

thanks
Prashanth

**Comment by indygreg** [comment]
The CFFI bindings are lacking significantly behind the C extension. That's the bad news.

The good news is I'm adding zstd support to Mercurial and that will require CFFI support for PyPy compatibility. So I'll likely get around to improving the CFFI bindings in the next month or so. That is, unless someone submits a pull request to do it first :)

**Comment by indygreg** [comment]
As of today, zstd_cffi.py should now have feature parity with the C extension (or at least be close to it). All tests run and pass on both the C extension and CFFI implementations. If the implementations vary in any way, I consider that a bug.

I want to perform a thorough review of the CFFI implementation before cutting the next release, however. Although, there's a chance I release 0.7 with the caveat that CFFI support is still considered alpha.
