### ISSUE TITLE
Upgrade zstd to the latest git

### ISSUE THREAD

**Issue by KOLANICH** [indygreg/python-zstandard#90]
Tests mostly pass with respect to changes in error messages, version. The only thing I not qquit3 sure how to interpret is changes in results hashes. I haven't investigated that, but IMHO more meaningful testing of that is needed rather than comparing hashes.

**Comment by indygreg** [comment]
`master` now is using zstd 1.4.3, the latest release. I may cut a 0.12 release in the next few days.
