### ISSUE TITLE
Packaging metadata entries (cffi dependency) are inconsistent in published artifacts

### ISSUE THREAD

**Issue by himikof** [indygreg/python-zstandard#97]
It seems like the `cffi` dependency is a bit "auto-magical" (as in, it is used if found during build by default, and not needed/used in many cases) in this package.

This behavior leads to inconsistent dependency metadata in the published artifacts:
sdist is currently built without a cffi library available, so it does not contain a `Requires-Dist: cffi` entry. Binary wheels on all platforms (both CPython and PyPy) currently are always built with `cffi` available, so the wheels appropriately contain `Requires-Dist: cffi` entry.
To make matters worse, it seems that PyPI (Warehouse) when exposing the metadata for the package in the JSON API will always use the metadata from the first uploaded artifact, so whether the metadata in the PyPI API has the `cffi` requirement will depend on the CI pipeline timing. Currently, the sdist (unsurprisingly) gets there first, so the PyPI API is missing the dependency.

And in the run-time on CPython the default policy of never using the cffi makes this issue largely unnoticed, even if the package manager gets confused and installs the binary wheel without cffi dependency. I have found this problem while debugging Poetry silently missing the dependency and failing to pin it in the lock file, which then has tripped independent consistency checks in `pip wheel`.

I understand that you want the library to just work in most use cases and different environments, therefore the two separate implementations, and even configurable import-time selection. But I think the distribution metadata needs to be consistent: your published artifacts either depend on the cffi library unconditionally, or the "extras" and "environment markers" mechanisms should be used to make it explicitly conditional (for example, requiring it unconditionally on PyPy and behind an extra option on CPython).

**Comment by indygreg** [comment]
Thank you for filing this issue. You've enlightened me about the existence of a Python packaging/distribution issue I wasn't aware of.

I'll have to do some research and then likely tweak behavior accordingly.
